### ISSUE TITLE
Incorrect MAC address

### ISSUE THREAD

**Issue by masterflitzer** [Berrysoft/mac_address#1]
Hi,

on my raspberry pi 4b (linux debian 11) i get the loopback mac address `00:00:00:00:00:00` from `get_mac_address()` which is undesirable/useless
on my windows 11 machine it works without a problem but in wsl (linux debian 11 inside windows) i have the same problem

sadly i have to revert to the upstream crate as long as this fork has this bug with non-windows machines

i used the following code for checking:

**Cargo.toml**
```toml
[package]
name = "test_mac"
version = "0.1.0"
edition = "2021"

[dependencies]
mac_address = "1.1.4"
mac_address2 = "2.0.0"
```

**src/main.rs**
```rust
use mac_address::get_mac_address;
use mac_address2::get_mac_address as get_mac_address2;

fn main() {
    match get_mac_address() {
        Ok(Some(ma)) => {
            println!("mac => {}", ma);
            println!("bytes => {:?}", ma.bytes());
        }
        Ok(None) => println!("No MAC address found."),
        Err(e) => println!("{:?}", e),
    }
    match get_mac_address2() {
        Ok(Some(ma)) => {
            println!("mac2 => {}", ma);
            println!("bytes2 => {:?}", ma.bytes());
        }
        Ok(None) => println!("No MAC address found."),
        Err(e) => println!("{:?}", e),
    }
}
```

Output (censored but the issue is visible):
```
mac => 00:15:5D:XX:XX:XX
bytes => [0, 21, 93, x, x, x]
mac2 => 00:00:00:00:00:00
bytes2 => [0, 0, 0, 0, 0, 0]
```

upstream (**mac_address**) doesn't seem to have the same problem (even tho there is a similar open issue which i cannot reproduce)
for me only this fork (**mac_address2**) seems to be affected

related : https://github.com/repnop/mac_address/issues/33

**Comment by Berrysoft** [comment]
Check the version 2.0.2 please. If there's still the same problem, feel free to reopen.
